name: Fleet Config

on:
  push:
    branches:
    - '3.*'
    paths:
    - '.github/workflows/fleet-config.yml'

  workflow_dispatch:

jobs:
  build_fleet_config:
    name: Build Fleet Config
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to the container registry
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: saltworks/saltminer
          tags: |
            type=raw,value=fleet-config-${{ github.ref_name }}.{{date 'YYYYMMDD-HHmmss' tz='America/Chicago'}}
          labels: |
            org.opencontainers.image.title=fleet-config
            org.opencontainers.image.description=SaltMiner Fleet Configuration
            org.opencontainers.image.vendor=Saltworks Security, LLC

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6.15.0
        with:
          file: .dockerfiles/Dockerfile-fleet-config
          context: .dockerfiles
          push: false
          provenance: mode=max
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
