name: Package SaltMiner Setup

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir output
          cp -r * output/
          rm output/README.md
          rm -rf output/.git
          rm -rf output/.github
          rm output/.gitignore
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: saltminer-setup-${{ github.ref_name }}
          path: ./output
          retention-days: 30
          # Needed for .env file
          include-hidden-files: true
