name: Package SaltMiner Setup

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - '3.*'
    paths-ignore:
    - '.github/workflows/fleet-config.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          mkdir output
          cp .env output/
          cp -r config output/
          cp docker-compose.yml output/
          cp fleet.env output/
          cp paths-cloud.sh output/
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: saltminer-setup-${{ github.ref_name }}.{{date 'YYYYMMDD-HHmmss' tz='America/Chicago'}}
          path: ./output
          retention-days: 30
          # Needed for .env file
          include-hidden-files: true
