name: Package SaltMiner Setup

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
    - main
    - '3.*'
    paths-ignore:
    - '.github/workflows/fleet-config.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  package:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}
      ARTIFACT_NAME: saltminer-setup-${{ github.ref_name }}-${{ github.run_number }}
      TAG: v${{ github.ref_name }}-alpha.${{ github.run_number }}

    steps:
    - uses: actions/checkout@v4
    - name: Collect artifact files
      run: |
        mkdir output
        cp .env output/
        cp -r config output/
        cp docker-compose.yml output/
        cp fleet.env output/
        cp paths-cloud.sh output/
    - name: Upload a Build Artifact
      id: artifact-upload-step
      uses: actions/upload-artifact@v4.6.2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ./output
        retention-days: 30
        # Needed for .env file
        include-hidden-files: true
    - name: Create Release
#      env:
#       GH_TOKEN: ${{ github.token }}
      run: |
        gh release create ${{ env.TAG }} \
          --repo="$GITHUB_REPOSITORY" \
          --title=${{ env.TAG }} \
          --latest=false \
          --prerelease=true \
          --notes="SaltMiner ${{ env.TAG }} setup project."
    - name: debug
      run: |
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/actions/artifacts/${{ steps.artifact-upload-step.outputs.artifact-id }}/zip
        pwd
        ls -la
        ls -la output
